project:
  type: manuscript
  render:
    - index.qmd

manuscript:
  article: index.qmd

format:
  html:
    number-sections: true
    number-depth: 5
    toc-expand: 1
    theme:
      light: cosmo
      dark: solar
    mainfont: system-ui

  # (other formats)
  # pdf: default

execute:
  freeze: true


